import time
import os
import os.path
import os, platform
print ("Enhanced ChatBot Communication System Setup")
time.sleep (1)
print ("Samuel Matthews, 2021")
time.sleep (1)
print ("Unauthorised reproduction of this software is prohibited")
time.sleep (1)
proceed = input ("To continue with the Enhanced ChatBot Communication System, you must agree to the storage and use of any information entered into this system. Press y to agree, or n to disagree: ")
if proceed != ("y"):
    quit()
if proceed == ("y"):
    print ("Hi there!")
    time.sleep (1)
    print ("Welcome to the Enhanced ChatBot Communication System, or ECCS for short! This program is a concept, currently in development by Samuel Matthews.")
    time.sleep (1)
    print ("Since the ECCS runs completely offline, no data is uploaded to the web at all, and the system will still retain full functionality, even when disconnected from the internet")
    time.sleep (1)
    print ("Let's get on with it, then.")
    path = input ("Please paste in the filepath for where you want the ECCS data to be stored: ")
    os.mkdir(path + "\ECCSData")
    path = (path + "\ECCSData")
    time.sleep (1)
    print ("Okay, cool.")
    name = input ("Please enter your full name here: ")
    print ("Hello " + name)
    save_path = (path)
    file_name = ("name.txt")
    completeName = os.path.join(save_path, file_name)
    file1 = open(completeName, "a+")
    file1.write(name)
    file1.close()
    DOB = input ("Now that I have your name, when were you born? Please answer in either D/M/Y or M/D/Y format: ")
    save_path = (path)
    file_name = ("DOB.txt")
    completeName = os.path.join(save_path, file_name)
    file1 = open(completeName, "a+")
    file1.write(DOB)
    file1.close()
    FavColour = input ("So " + name +", what's your favourite colour? ")
    save_path = (path)
    file_name = ("FavColour.txt")
    completeName = os.path.join(save_path, file_name)
    file1 = open(completeName, "a+")
    file1.write(FavColour)
    file1.close()
    datapath = ("C:\ECCS")
    os.mkdir(path)
    f= open("filepath.txt","w+")
    for i in range(1):
        f.write(path, "\ECCSData")
        f.close()
    time.sleep (3)
